version: "3.8"

services:
  frontend:
    container_name: book_project_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        PROFILE: ${PROFILE}
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - backend
  db:
    image: postgres:14 # 14 is the latest Flyway supported version
    container_name: book_project_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
  backend:
    container_name: book_project_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        mvn_arg: clean package -DskipTests
        DB_HOSTNAME: book_project_db
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    restart: "no"
    ports: 
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5433
    depends_on:
      - db

